### ISSUE TITLE
Avoid exception for objects with 'patternProperties' only    

### ISSUE THREAD

**Issue by edugomez** [open-contracting/ocds-tabulate#5]
An extension may have only ```"patternProperties"``` in an object type (e.g. https://github.com/open-contracting/ocds_metrics_extension/blob/master/release-schema.json#L171), which currently raises an exception.

**Comment by edugomez** [comment]
@jpmckinney Trying to push branch with fix for this issue, but I don't seem to have permission to do so.

**Comment by jpmckinney** [comment]
I've now added that repo to the Developers team.

**Comment by jpmckinney** [comment]
Closed by #6
